common: &common
  adapter: postgresql

development:
  <<: *common
  database: textyourcity_dev
  host: localhost


test:
  <<: *common
  database: textyourcity_test
  host: localhost

production:
  <<: *common
  database: textyourcity_production
